---
title: "LLP_comparison"
author: "Kenneth Matreyek"
date: "3/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## R Markdown
```{r}
input_data <- read.csv(file = "All_in_one_200702.csv", header = T, stringsAsFactors = F)

data_plotting <- input_data

data_plotting$cells <- factor(data_plotting$cells, levels = c("Int-Blast","iCasp9-Blast","G542A"))
data_plotting$bxb1 <- factor(data_plotting$bxb1, levels = c("none","added"))
data_plotting$selection <- factor(data_plotting$selection, levels = c("none","ap1903"))

data_plotting$single_recombinants <- data_plotting$red + data_plotting$green

LLP_comparison_plot <- ggplot() + theme_bw() + 
  geom_point(data = data_plotting, aes(x = cells, y = single_recombinants, shape = bxb1), color = "black") +
  facet_grid(cols = vars(selection)) +
  scale_shape_manual(values = c(1,16)) +
  xlab(NULL) + ylab("Percent single recombinants")
ggsave(file = "LLP_comparison_plot_200702.pdf", height = 3, width = 6)

LLP_comparison_plot
```

